### ISSUE TITLE
dataloader.py データ数を絞らない方が良い

### ISSUE THREAD

**Issue by OsugiTakuya** [ex-hasuolab/class-activation-map#14]
[dataloader.py](https://github.com/ex-hasuolab/class-activation-map/blob/master/dataloader.py) 50~56行目  
普通に学習しようとすると、500データでは少なすぎた。  
(引数から設定できるようにできたら良い？)

**Comment by TakehikoEsaka** [comment]
checkpoint作れるか試したかったんでハードコーディングしてました！
引数chopprinが作っときます。

**Comment by OsugiTakuya** [comment]
なるほど。。  
お試しでデータ数絞ってただけなら、特にデータ絞る必要はなさそうなので引数作らなくても良いと思います。  
(データ数を少なくしたい人は、dataloaderインスタンスを作ってから絞るってことで良いかなと)

**Comment by OsugiTakuya** [comment]
Google Colaboratoryでのデバッグのものが残っていたということで理解
