### ISSUE TITLE
dataloaderスペルミス

### ISSUE THREAD

**Issue by OsugiTakuya** [ex-hasuolab/class-activation-map#8]
[dataloder.py](https://github.com/ex-hasuolab/class-activation-map/blob/master/dataloder.py)→dataloader.py にすべき

**Comment by TakehikoEsaka** [comment]
Thank you !
[feature/#8/#12/20200602/esakaブランチ](https://github.com/ex-hasuolab/class-activation-map/tree/feature/%238/%2312/20200602/chopprin)で対応しときます！

**Comment by TakehikoEsaka** [comment]
masterにマージしときました
